apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-example-app-consumer
spec:
  template:
    spec:
      containers:
      - name: kafka-example-app-consumer
        image: kruczjak/kafka-example-app:latest
        command:
        - ./main
        - "-worker_type"
        - "consumer"
        - "-brokers"
        - "my-kafka-kafka-headless.kafka.svc.cluster.local:9092"
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-example-app-producer
spec:
  template:
    spec:
      containers:
      - name: kafka-example-app-producer
        image: kruczjak/kafka-example-app:latest
        command:
        - ./main
        - "-worker_type"
        - "producer"
        - "-brokers"
        - "my-kafka-kafka-headless.kafka.svc.cluster.local:9092"
        - "-messages"
        - "2147480000"
      restartPolicy: Never
  backoffLimit: 0
