apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: kafka
    prometheus: kube-prometheus
  name: my-kafka-kafka
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: jmx-exporter
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kafka
  selector:
    matchLabels:
      app: kafka
      release: my-kafka
